name: ESP IDF Build
run-name: Build ESP-IDF Project
on: [push]
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - name: esp-idf build
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: v5.4
        target: esp32c6
        path: '.'
  cppcheck:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Install Cppcheck
      - name: Install Cppcheck
        run: sudo apt-get install -y cppcheck

      # Run Cppcheck
      - name: Run Cppcheck
        run: cppcheck --enable=all --inconclusive --std=c++23 --quiet --project=compile_commands.json .
